nohup: ignoring input
INFO:root:Downloading and generating the schema...
INFO:root:Generated the schema for 2019_05_13. A database will be created at mysql+pymysql://innovationMaster:innovationmapping@innovation-mapping-mysql-mysql5721.ci9272ypsbyf.eu-west-2.rds.amazonaws.com/patstat_2019_05_13
INFO:root:Skipping download/files/2019/05/13/1557744759414/index_documentation_scripts_PATSTAT_Global_2019_Spring.zip
INFO:root:Skipping download/files/2019/05/13/1557744782230/data_PATSTAT_Global_2019_Spring_01.zip
INFO:root:Skipping download/files/2019/05/13/1557746142379/data_PATSTAT_Global_2019_Spring_02.zip
INFO:root:Skipping download/files/2019/05/13/1557747404920/data_PATSTAT_Global_2019_Spring_03.zip
INFO:root:Skipping download/files/2019/05/13/1557748373770/data_PATSTAT_Global_2019_Spring_04.zip
INFO:root:Skipping download/files/2019/05/13/1557750095304/data_PATSTAT_Global_2019_Spring_05.zip
INFO:root:Processing file download/files/2019/05/13/1557751862915/data_PATSTAT_Global_2019_Spring_06.zip...
INFO:root:		Skipping tls212_part02.zip
INFO:root:		Skipping tls214_part01.zip
INFO:root:		Skipping tls214_part02.zip
INFO:root:		Skipping tls215_part01.zip
INFO:root:		Skipping tls216_part01.zip
INFO:root:	Processing nested file tls222_part01.zip...
INFO:root:		Retrieved class from table name tls222.
Traceback (most recent call last):
  File "data_loader.py", line 249, in <module>
    n_jobs=1)
  File "data_loader.py", line 236, in download_patstat_to_db
    pwd=patstat_pwd)
  File "data_loader.py", line 205, in _download_patstat_to_db
    restart_filename=restart_filename)
  File "data_loader.py", line 167, in zipfile_to_db
    for rows in iterchunks(z, chunksize=chunksize):
  File "data_loader.py", line 26, in iterchunks
    with BytesIO(zipped_csv.read()) as zio:
  File "/home/ec2-user/miniconda3/envs/py36a/lib/python3.6/zipfile.py", line 858, in read
    buf += self._read1(self.MAX_N)
  File "/home/ec2-user/miniconda3/envs/py36a/lib/python3.6/zipfile.py", line 940, in _read1
    data += self._read2(n - len(data))
  File "/home/ec2-user/miniconda3/envs/py36a/lib/python3.6/zipfile.py", line 972, in _read2
    data = self._fileobj.read(n)
  File "/home/ec2-user/miniconda3/envs/py36a/lib/python3.6/zipfile.py", line 729, in read
    data = self._file.read(n)
MemoryError
